### ISSUE TITLE
YAML payload

### ISSUE THREAD

**Issue by saiyam1814** [saiyam1814/tweets#3]
```yaml
name: Hello World
id: 100
description: A simple hello world example
tags:
  - good first issue
  - needs triage
  - bug
```
